Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -57,15 +57,14 @@ stages:
       workingDirectory: infra
 
     - script: |
-        plan_exit_code=$?
-        echo "Plan exit code: $plan_exit_code"
-        if [ $plan_exit_code -eq 2 ]
-        then
+       if [ $(plan_exit_code) -eq 2 ]
+       then
           echo "Applying Terraform Plan..."
-          terraform apply tfplan
-        elif [ $plan_exit_code -eq 0 ]
+          terraform apply "tfplan"
+        elif [ $(plan_exit_code) -eq 0 ]
           then
             echo "No changes detected in Terraform Plan."
           else
-            exit 1 # Exit the pipeline as failed if Terraform plan failed to execute
+            echo "Terraform Plan failed."
+          exit 1 
       displayName: 'Conditional Terraform Apply'
